
services:
  petclinic-app:
    image: officialdarnyc/petclinic-app:v1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      restart_policy:
        condition: on-failure
    ports:
      - 8080-8081:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://sqlserver/petclinic
    volumes:
      - ./:/app
    networks:
      - petclinic
    depends_on:
      - sqlserver    
  sqlserver:
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic

networks:
  petclinic:
    driver: bridge
